/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ATTESTATION_EXPIRY"
      | "ATTESTATION_VERIFIER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MIN_SYNDICATE_REPUTATION"
      | "REGISTRAR_ROLE"
      | "activeAgentCount"
      | "addCapability"
      | "agentIdByWallet"
      | "agents"
      | "agentsByOwner"
      | "allAgentIds"
      | "getAgent"
      | "getAgentsByOwner"
      | "getCapabilities"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isAttestationValid"
      | "isSyndicateEligible"
      | "registerAgent"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "totalAgents"
      | "updateReputation"
      | "updateStatus"
      | "verifyAttestation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentStatusUpdated"
      | "AttestationUpdated"
      | "CapabilityAdded"
      | "CapabilityRemoved"
      | "ReputationUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ATTESTATION_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ATTESTATION_VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SYNDICATE_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRAR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCapability",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "agentIdByWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "agentsByOwner",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allAgentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAgentsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapabilities",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAttestationValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSyndicateEligible",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, AddressLike, BytesLike, BigNumberish, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestation",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ATTESTATION_EXPIRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ATTESTATION_VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_SYNDICATE_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRAR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentIdByWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allAgentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAttestationValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSyndicateEligible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestation",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    owner: AddressLike,
    agentWallet: AddressLike,
    agentType: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    owner: string,
    agentWallet: string,
    agentType: bigint
  ];
  export interface OutputObject {
    agentId: string;
    owner: string;
    agentWallet: string;
    agentType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusUpdatedEvent {
  export type InputTuple = [agentId: BytesLike, status: BigNumberish];
  export type OutputTuple = [agentId: string, status: bigint];
  export interface OutputObject {
    agentId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationUpdatedEvent {
  export type InputTuple = [agentId: BytesLike, attestationHash: BytesLike];
  export type OutputTuple = [agentId: string, attestationHash: string];
  export interface OutputObject {
    agentId: string;
    attestationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilityAddedEvent {
  export type InputTuple = [agentId: BytesLike, capability: string];
  export type OutputTuple = [agentId: string, capability: string];
  export interface OutputObject {
    agentId: string;
    capability: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilityRemovedEvent {
  export type InputTuple = [agentId: BytesLike, capability: string];
  export type OutputTuple = [agentId: string, capability: string];
  export interface OutputObject {
    agentId: string;
    capability: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [agentId: BytesLike, newScore: BigNumberish];
  export type OutputTuple = [agentId: string, newScore: bigint];
  export interface OutputObject {
    agentId: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ATTESTATION_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  ATTESTATION_VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MIN_SYNDICATE_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  REGISTRAR_ROLE: TypedContractMethod<[], [string], "view">;

  activeAgentCount: TypedContractMethod<[], [bigint], "view">;

  addCapability: TypedContractMethod<
    [agentId: BytesLike, capability: string],
    [void],
    "nonpayable"
  >;

  agentIdByWallet: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  agents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string
      ] & {
        agentId: string;
        owner: string;
        agentWallet: string;
        publicKey: string;
        agentType: bigint;
        status: bigint;
        registeredAt: bigint;
        lastAttestation: bigint;
        attestationHash: string;
        reputationScore: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;

  agentsByOwner: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  allAgentIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getAgent: TypedContractMethod<
    [agentId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        owner: string;
        agentWallet: string;
        agentType: bigint;
        status: bigint;
        registeredAt: bigint;
        reputationScore: bigint;
        attestationValid: boolean;
      }
    ],
    "view"
  >;

  getAgentsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getCapabilities: TypedContractMethod<
    [agentId: BytesLike],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAttestationValid: TypedContractMethod<
    [agentId: BytesLike],
    [boolean],
    "view"
  >;

  isSyndicateEligible: TypedContractMethod<
    [agentId: BytesLike],
    [boolean],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [
      agentId: BytesLike,
      agentWallet: AddressLike,
      publicKey: BytesLike,
      agentType: BigNumberish,
      capabilities: string[],
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  updateReputation: TypedContractMethod<
    [agentId: BytesLike, delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [agentId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyAttestation: TypedContractMethod<
    [agentId: BytesLike, attestationHash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ATTESTATION_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ATTESTATION_VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_SYNDICATE_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGISTRAR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addCapability"
  ): TypedContractMethod<
    [agentId: BytesLike, capability: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentIdByWallet"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string
      ] & {
        agentId: string;
        owner: string;
        agentWallet: string;
        publicKey: string;
        agentType: bigint;
        status: bigint;
        registeredAt: bigint;
        lastAttestation: bigint;
        attestationHash: string;
        reputationScore: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agentsByOwner"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "allAgentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        owner: string;
        agentWallet: string;
        agentType: bigint;
        status: bigint;
        registeredAt: bigint;
        reputationScore: bigint;
        attestationValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentsByOwner"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCapabilities"
  ): TypedContractMethod<[agentId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAttestationValid"
  ): TypedContractMethod<[agentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSyndicateEligible"
  ): TypedContractMethod<[agentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      agentWallet: AddressLike,
      publicKey: BytesLike,
      agentType: BigNumberish,
      capabilities: string[],
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agentId: BytesLike, delta: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [agentId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAttestation"
  ): TypedContractMethod<
    [agentId: BytesLike, attestationHash: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusUpdated"
  ): TypedContractEvent<
    AgentStatusUpdatedEvent.InputTuple,
    AgentStatusUpdatedEvent.OutputTuple,
    AgentStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationUpdated"
  ): TypedContractEvent<
    AttestationUpdatedEvent.InputTuple,
    AttestationUpdatedEvent.OutputTuple,
    AttestationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CapabilityAdded"
  ): TypedContractEvent<
    CapabilityAddedEvent.InputTuple,
    CapabilityAddedEvent.OutputTuple,
    CapabilityAddedEvent.OutputObject
  >;
  getEvent(
    key: "CapabilityRemoved"
  ): TypedContractEvent<
    CapabilityRemovedEvent.InputTuple,
    CapabilityRemovedEvent.OutputTuple,
    CapabilityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(bytes32,address,address,uint8)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusUpdated(bytes32,uint8)": TypedContractEvent<
      AgentStatusUpdatedEvent.InputTuple,
      AgentStatusUpdatedEvent.OutputTuple,
      AgentStatusUpdatedEvent.OutputObject
    >;
    AgentStatusUpdated: TypedContractEvent<
      AgentStatusUpdatedEvent.InputTuple,
      AgentStatusUpdatedEvent.OutputTuple,
      AgentStatusUpdatedEvent.OutputObject
    >;

    "AttestationUpdated(bytes32,bytes32)": TypedContractEvent<
      AttestationUpdatedEvent.InputTuple,
      AttestationUpdatedEvent.OutputTuple,
      AttestationUpdatedEvent.OutputObject
    >;
    AttestationUpdated: TypedContractEvent<
      AttestationUpdatedEvent.InputTuple,
      AttestationUpdatedEvent.OutputTuple,
      AttestationUpdatedEvent.OutputObject
    >;

    "CapabilityAdded(bytes32,string)": TypedContractEvent<
      CapabilityAddedEvent.InputTuple,
      CapabilityAddedEvent.OutputTuple,
      CapabilityAddedEvent.OutputObject
    >;
    CapabilityAdded: TypedContractEvent<
      CapabilityAddedEvent.InputTuple,
      CapabilityAddedEvent.OutputTuple,
      CapabilityAddedEvent.OutputObject
    >;

    "CapabilityRemoved(bytes32,string)": TypedContractEvent<
      CapabilityRemovedEvent.InputTuple,
      CapabilityRemovedEvent.OutputTuple,
      CapabilityRemovedEvent.OutputObject
    >;
    CapabilityRemoved: TypedContractEvent<
      CapabilityRemovedEvent.InputTuple,
      CapabilityRemovedEvent.OutputTuple,
      CapabilityRemovedEvent.OutputObject
    >;

    "ReputationUpdated(bytes32,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
