/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SyndicateVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "SYNDICATE_ADMIN_ROLE"
      | "addMember"
      | "agentRegistry"
      | "allSyndicateIds"
      | "createSyndicate"
      | "depositETH"
      | "depositToken"
      | "distributeProfits"
      | "ethTreasury"
      | "executeProposal"
      | "getMemberCount"
      | "getRoleAdmin"
      | "getTreasuryBalance"
      | "grantRole"
      | "hasRole"
      | "hasVoted"
      | "memberList"
      | "members"
      | "proposalCounter"
      | "proposals"
      | "renounceRole"
      | "requestMembership"
      | "revokeRole"
      | "supportsInterface"
      | "syndicates"
      | "totalSyndicates"
      | "treasury"
      | "vote"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositReceived"
      | "MemberJoined"
      | "MemberLeft"
      | "ProfitsDistributed"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SyndicateCreated"
      | "Voted"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SYNDICATE_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMember",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allSyndicateIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSyndicate",
    values: [
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeProfits",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ethTreasury",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryBalance",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberList",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCounter",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMembership",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "syndicates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSyndicates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasury",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SYNDICATE_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allSyndicateIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSyndicate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeProfits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "memberList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMembership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "syndicates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSyndicates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositReceivedEvent {
  export type InputTuple = [
    syndicateId: BytesLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    syndicateId: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    syndicateId: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [syndicateId: BytesLike, agentId: BytesLike];
  export type OutputTuple = [syndicateId: string, agentId: string];
  export interface OutputObject {
    syndicateId: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberLeftEvent {
  export type InputTuple = [syndicateId: BytesLike, agentId: BytesLike];
  export type OutputTuple = [syndicateId: string, agentId: string];
  export interface OutputObject {
    syndicateId: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitsDistributedEvent {
  export type InputTuple = [syndicateId: BytesLike, totalAmount: BigNumberish];
  export type OutputTuple = [syndicateId: string, totalAmount: bigint];
  export interface OutputObject {
    syndicateId: string;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    syndicateId: BytesLike,
    proposalId: BytesLike,
    proposalType: BigNumberish
  ];
  export type OutputTuple = [
    syndicateId: string,
    proposalId: string,
    proposalType: bigint
  ];
  export interface OutputObject {
    syndicateId: string;
    proposalId: string;
    proposalType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [
    syndicateId: BytesLike,
    proposalId: BytesLike,
    success: boolean
  ];
  export type OutputTuple = [
    syndicateId: string,
    proposalId: string,
    success: boolean
  ];
  export interface OutputObject {
    syndicateId: string;
    proposalId: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SyndicateCreatedEvent {
  export type InputTuple = [
    syndicateId: BytesLike,
    name: string,
    founder: AddressLike
  ];
  export type OutputTuple = [
    syndicateId: string,
    name: string,
    founder: string
  ];
  export interface OutputObject {
    syndicateId: string;
    name: string;
    founder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    agentId: BytesLike,
    approve: boolean
  ];
  export type OutputTuple = [
    proposalId: string,
    agentId: string,
    approve: boolean
  ];
  export interface OutputObject {
    proposalId: string;
    agentId: string;
    approve: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    syndicateId: BytesLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    syndicateId: string,
    token: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    syndicateId: string;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SyndicateVault extends BaseContract {
  connect(runner?: ContractRunner | null): SyndicateVault;
  waitForDeployment(): Promise<this>;

  interface: SyndicateVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  SYNDICATE_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addMember: TypedContractMethod<
    [syndicateId: BytesLike, agentId: BytesLike, votingPower: BigNumberish],
    [void],
    "nonpayable"
  >;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  allSyndicateIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createSyndicate: TypedContractMethod<
    [
      syndicateId: BytesLike,
      name: string,
      minReputation: BigNumberish,
      maxMembers: BigNumberish,
      votingThresholdBps: BigNumberish,
      proposalDuration: BigNumberish,
      syndicateFeeBps: BigNumberish,
      requiresProof: boolean
    ],
    [void],
    "nonpayable"
  >;

  depositETH: TypedContractMethod<[syndicateId: BytesLike], [void], "payable">;

  depositToken: TypedContractMethod<
    [syndicateId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeProfits: TypedContractMethod<
    [syndicateId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ethTreasury: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  executeProposal: TypedContractMethod<
    [syndicateId: BytesLike, proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  getMemberCount: TypedContractMethod<
    [syndicateId: BytesLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTreasuryBalance: TypedContractMethod<
    [syndicateId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  memberList: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  members: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        agentId: string;
        joinedAt: bigint;
        votingPower: bigint;
        contribution: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  proposalCounter: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        proposalId: string;
        proposalType: bigint;
        targetAgentId: string;
        data: string;
        proposer: string;
        createdAt: bigint;
        deadline: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestMembership: TypedContractMethod<
    [syndicateId: BytesLike, agentId: BytesLike],
    [string],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  syndicates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        syndicateId: string;
        name: string;
        founder: string;
        minReputation: bigint;
        maxMembers: bigint;
        votingThresholdBps: bigint;
        proposalDuration: bigint;
        syndicateFeeBps: bigint;
        requiresProof: boolean;
        active: boolean;
      }
    ],
    "view"
  >;

  totalSyndicates: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  vote: TypedContractMethod<
    [
      syndicateId: BytesLike,
      proposalId: BytesLike,
      agentId: BytesLike,
      approve: boolean
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [
      syndicateId: BytesLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SYNDICATE_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [syndicateId: BytesLike, agentId: BytesLike, votingPower: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allSyndicateIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createSyndicate"
  ): TypedContractMethod<
    [
      syndicateId: BytesLike,
      name: string,
      minReputation: BigNumberish,
      maxMembers: BigNumberish,
      votingThresholdBps: BigNumberish,
      proposalDuration: BigNumberish,
      syndicateFeeBps: BigNumberish,
      requiresProof: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositETH"
  ): TypedContractMethod<[syndicateId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [syndicateId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeProfits"
  ): TypedContractMethod<
    [syndicateId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ethTreasury"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<
    [syndicateId: BytesLike, proposalId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMemberCount"
  ): TypedContractMethod<[syndicateId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTreasuryBalance"
  ): TypedContractMethod<
    [syndicateId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "memberList"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        agentId: string;
        joinedAt: bigint;
        votingPower: bigint;
        contribution: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalCounter"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        proposalId: string;
        proposalType: bigint;
        targetAgentId: string;
        data: string;
        proposer: string;
        createdAt: bigint;
        deadline: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestMembership"
  ): TypedContractMethod<
    [syndicateId: BytesLike, agentId: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "syndicates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        syndicateId: string;
        name: string;
        founder: string;
        minReputation: bigint;
        maxMembers: bigint;
        votingThresholdBps: bigint;
        proposalDuration: bigint;
        syndicateFeeBps: bigint;
        requiresProof: boolean;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSyndicates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [
      syndicateId: BytesLike,
      proposalId: BytesLike,
      agentId: BytesLike,
      approve: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      syndicateId: BytesLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DepositReceived"
  ): TypedContractEvent<
    DepositReceivedEvent.InputTuple,
    DepositReceivedEvent.OutputTuple,
    DepositReceivedEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MemberLeft"
  ): TypedContractEvent<
    MemberLeftEvent.InputTuple,
    MemberLeftEvent.OutputTuple,
    MemberLeftEvent.OutputObject
  >;
  getEvent(
    key: "ProfitsDistributed"
  ): TypedContractEvent<
    ProfitsDistributedEvent.InputTuple,
    ProfitsDistributedEvent.OutputTuple,
    ProfitsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SyndicateCreated"
  ): TypedContractEvent<
    SyndicateCreatedEvent.InputTuple,
    SyndicateCreatedEvent.OutputTuple,
    SyndicateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "DepositReceived(bytes32,address,uint256)": TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;
    DepositReceived: TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;

    "MemberJoined(bytes32,bytes32)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "MemberLeft(bytes32,bytes32)": TypedContractEvent<
      MemberLeftEvent.InputTuple,
      MemberLeftEvent.OutputTuple,
      MemberLeftEvent.OutputObject
    >;
    MemberLeft: TypedContractEvent<
      MemberLeftEvent.InputTuple,
      MemberLeftEvent.OutputTuple,
      MemberLeftEvent.OutputObject
    >;

    "ProfitsDistributed(bytes32,uint256)": TypedContractEvent<
      ProfitsDistributedEvent.InputTuple,
      ProfitsDistributedEvent.OutputTuple,
      ProfitsDistributedEvent.OutputObject
    >;
    ProfitsDistributed: TypedContractEvent<
      ProfitsDistributedEvent.InputTuple,
      ProfitsDistributedEvent.OutputTuple,
      ProfitsDistributedEvent.OutputObject
    >;

    "ProposalCreated(bytes32,bytes32,uint8)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(bytes32,bytes32,bool)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SyndicateCreated(bytes32,string,address)": TypedContractEvent<
      SyndicateCreatedEvent.InputTuple,
      SyndicateCreatedEvent.OutputTuple,
      SyndicateCreatedEvent.OutputObject
    >;
    SyndicateCreated: TypedContractEvent<
      SyndicateCreatedEvent.InputTuple,
      SyndicateCreatedEvent.OutputTuple,
      SyndicateCreatedEvent.OutputObject
    >;

    "Voted(bytes32,bytes32,bool)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;

    "Withdrawal(bytes32,address,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
